apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment

spec:
  selector:
    matchLabels:
      app: k8s-study-redis

  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-study-redis
    spec:
      containers:
        - name: k8s-study-redis
          image: redis:5.0.5-alpine

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service

spec:
  type: LoadBalancer
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: k8s-study-redis

  ports:
    - port: 6379
      nodePort: 32080
