apiVersion: v1
kind: Service
metadata:
  name: k8s-study-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: k8s-study-app

  ports:
    - name: http
      port: 4000
      nodePort: 32000

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: service-k8s-study
spec:
  type: LoadBalancer
  ports:
    - port: 4000
  selector:
    name: app-k8s-study
