apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-study-deployment

spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: k8s-study-app

  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: k8s-study-app
    spec:
      containers:
        - name: k8s-study-app
          image: camiseta22/k8s-study:release-0.0.2
